### ISSUE TITLE
cmderr: exit status 2, ls: cannot access /proc/0/root/sys/class/net/: No such file or directory

### ISSUE THREAD

**Issue by ehsanmostajeran** [cilium-team/docker-collector#1]
Hi, I followed the guide available on this repo to run 3 containers (Collector, Elasticsearch and Logstach).
They all run in container but I get this error when I check collector container logs.

`2016/05/17 08:10:29 Trying to connect to ElasticSearch to '10.1.81.12':'9200'
2016/05/17 08:10:29 Success!
2016/05/17 08:10:29 Trying to connect to Logstash to '10.1.81.12:8080'
2016/05/17 08:10:29 Success!
08:10:30.339 main ▶ INFO 001 Trying to get docker client info
08:10:30.339 main ▶ INFO 002 Attempt 1...
08:10:34.765 main ▶ INFO 003 Connection successful
08:10:34.906 execShCmd ▶ ERRO 004 cmderr: exit status 2, ls: cannot access /proc/0/root/sys/class/net/: No such file or directory
08:10:34.917 execShCmd ▶ ERRO 005 cmderr: exit status 2, ls: cannot access /proc/0/root/sys/class/net/: No such file or directory
08:10:34.925 execShCmd ▶ ERRO 006 cmderr: exit status 2, ls: cannot access /proc/0/root/sys/class/net/: No such file or directory
08:10:34.931 execShCmd ▶ ERRO 007 cmderr: exit status 2, ls: cannot access /proc/0/root/sys/class/net/: No such file or directory
08:10:34.934 execShCmd ▶ ERRO 008 cmderr: exit status 2, ls: cannot access /proc/0/root/sys/class/net/: No such file or directory
08:10:35.006 execShCmd ▶ ERRO 009 cmderr: exit status 2, ls: cannot access /proc/0/root/sys/class/net/: No such file or directory
08:10:35.009 execShCmd ▶ ERRO 00a cmderr: exit status 2, ls: cannot access /proc/0/root/sys/class/net/: No such file or directory
08:10:35.012 execShCmd ▶ ERRO 00b cmderr: exit status 2, ls: cannot access /proc/0/root/sys/class/net/: No such file or directory
08:10:35.012 main ▶ INFO 00c docker-collector has started
`

**Comment by aanm** [comment]
Can you provide the exact commands that you executed so I can replicate this issue?

**Comment by ehsanmostajeran** [comment]
Commands are same as what provided by https://github.com/cilium-team/docker-collector#using-docker-collector. The error above is obtained from docker logs <collector-container>.

**Comment by aanm** [comment]
I've test all the commands and they work as expected.
I need more info, otherwise I'll close the issue.

``` bash
$ cd ~/github.com/cilium-team/docker-collector
$
$ export ELASTIC_SEARCH_IP=192.168.4.102
$ export LOGSTASH_IP=192.168.4.102
$ export LOGSTASH_PORT=8081
$
$ docker run -d --name docker-collector-elasticsearch -p 9200:9200 -p 9300:9300     elasticsearch:2.1.0 elasticsearch
$
$
$ docker run -d --name docker-collector-logstash -p $LOGSTASH_PORT:8080 \
     -v $PWD/configs/logstash.conf:/logstash.conf \
     logstash:2.1.0 logstash -f /logstash.conf
$
$ docker run -d --name docker-collector --privileged -h "$(hostname)" \
        --pid host -e ELASTIC_IP=$ELASTIC_SEARCH_IP \
        -e LOGSTASH_IP=$LOGSTASH_IP -e LOGSTASH_PORT=$LOGSTASH_PORT \
        -v /var/run/docker.sock:/var/run/docker.sock \
        cilium/docker-collector -f 'docker-collector.*'
$ 
$ docker logs docker-collector
2016/05/25 14:10:13 Trying to connect to ElasticSearch to '192.168.4.102':'9200'
2016/05/25 14:10:13 Success!
2016/05/25 14:10:13 Trying to connect to Logstash to '192.168.4.102:8081'
2016/05/25 14:10:13 Success!
14:10:13.691 main ▶ INFO 001 Trying to get docker client info
14:10:13.691 main ▶ INFO 002 Attempt 1...
14:10:13.785 main ▶ INFO 003 Connection successful
14:10:13.786 main ▶ INFO 004 docker-collector has started
14:10:13.787 readConfigFile ▶ INFO 005 Found configuration file '/docker-collector/configs/configs.json'
14:10:14.142 readConfigFile ▶ INFO 006 Found configuration file '/docker-collector/configs/templates.json'
14:10:14.180 readConfigFile ▶ INFO 007 Found configuration file '/docker-collector/configs/configs.json'
```

**Comment by ehsanmostajeran** [comment]
I have tested it again, works fine now. I guess problem was related to config files. It seems that in my first run config files were not available to the service.
Thanks for comments, and yes sure you may want to close this issue.
